spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai
  profiles:
    active: dev
  application:
    name: heartchain
  datasource:
    # 驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接的url
    url: jdbc:mysql://localhost:3306/ania
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 9
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode: console
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  reactive:
    session:
      cookie:
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  # 增强功能开启
  enable: true
  # 开启生产环境屏蔽（该选项配置后，无法访问页面）
  production: false
  # 开启Swagger的Basic认证功能,默认是false，配置后登录才可访问页面
  basic:
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456